config/routes.rb
Courseweblog::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :posts, only: [:index, :show]

  resources :categories, only: [:show]

  root :to => redirect("/posts/")

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :title

  has_many :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :description, :title, :category_id

  validates_presence_of :description, :title, :category_id

  belongs_to :category

  default_scope order("created_at DESC")
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :fetch_categories

  def fetch_categories
    @categories = Category.all
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  # GET /category/1
  # GET /category/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/show.html.erb
<h1><%= @category.title %></h1>

<%= render partial: "shared/post_in_list", collection: @category.posts, as: :post %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Courseweblog" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= tag "link", href: image_path("favicon.ico"), rel: "shortcut icon" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to "Courseweblog", root_path, class: "brand" %>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Posts", posts_url  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
        <div class="row">
           <div class="span9">
              <%= yield %>
            </div>
            <div class="span3">
              <div class="well sidebar-nav">
                <h3>Menu</h3>
                <ul class="nav nav-list">
                  <% if @categories.length > 0 %>
                    <li class="nav-header">Categories</li>
                  <% end %>
                  <% @categories.each do |category| %>
                    <li><%= link_to category.title, category_path(category) %></li>
                  <% end %>
                </ul>
              </div><!--/.well -->
            </div><!--/span-->
        </div><!--/row-->
      </div><!--/content-->

      <footer>
        <p>&copy; <%= link_to "Matteo Collina", "http://matteocollina.com" %> 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/posts/index.html.erb
<%- model_class = Post.new.class -%>
<h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>

<%= render partial: "shared/post_in_list", collection: @posts, as: :post %>

app/views/posts/show.html.erb
<h1><%= link_to @post.title, post_path(@post) %></h1>
<p>
  <small>Published at <%=l @post.created_at, format: :long %> in <%= link_to @post.category.title, category_url(@post.category) %></small>
</p>
<%= @post.description %>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              posts_path, :class => 'btn'  %>
</div>

app/views/shared/_post_in_list.html.erb
<h2><%= link_to post.title, post_path(post) %></h2>
<p>
  <small>Published at <%=l post.created_at, format: :long %> in <%= link_to post.category.title, post.category %></small>
</p>
<%= truncate(post.description, length: 500) %>
<p>
  <small><%= link_to "more", post_path(post) %></small>
</p>
<hr>